server:
  port: 8080

spring:
  datasource:
    username: root
    password: starjia072
    url: jdbc:mysql://localhost:3306/sakary?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml


logging:
  level:
    com:
      example:
        mapper: debug